### ISSUE TITLE
PL Inficon VGC.lvclass is broken while installing via VIPM Package v1.0.0.2

### ISSUE THREAD

**Issue by kavin1730** [plasmapper/inficon-vgc-labview#1]
All the VIs from the **PL Inficon VGC VIPM Package v1.0.0.2** are broken while we are opening it in LabVIEW.  

![image](https://github.com/user-attachments/assets/0b455c42-74d9-4661-88de-f325d8612e4d)
![image](https://github.com/user-attachments/assets/0f30feed-6f64-48f1-a678-8942a13f0943)

The error list shows that a VI named **“Read ?ontinuously Measured Values.vi"** was missing in the PL Inficon VGC.lvclass 

![image](https://github.com/user-attachments/assets/76f7418f-1ec9-46e0-844f-ac00f7d3ebd0)
![image](https://github.com/user-attachments/assets/c37b2fe7-2bee-417d-a5d3-d87d970f76e6)

### Workaround for this Issue:

1. Remove the missing VI from the class. 
2. Rename the VI as “Read Continuously Measured Values.vi” from the file explorer 
3. Add the renamed VI to the class. 
4. Save all the files in the PL Inficon VGC class.  

![image](https://github.com/user-attachments/assets/20b0accf-0e2b-4631-af6b-95d0e440a0ed)
![image](https://github.com/user-attachments/assets/258c32ee-82eb-4094-99f5-1f7969e52049)

This workaround will fix this issue and all the VIs from this class will be loaded in LabVIEW.
![image](https://github.com/user-attachments/assets/4187dd7d-6a3f-4ab9-8636-20f6095814d7)

### Solution for this Issue: 
1. Rename and add the missing VI in the PL Inficon VGC Class.
2. Build a VI Package with these updated class files. 
3. Release a new version of Package **v1.0.0.3** with these fixes in the VIPM.

**Comment by plasmapper** [comment]
Fixed (4bed9f0218003936bb4c73bfff8cf2a17265cd9e). Thank you.
